name: CI/CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: read
  actions: read
  checks: write
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3  # Обновлено с v2 до v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libsqlite3-dev libssl-dev
        sudo apt-get install -y libgtest-dev
        # Установка nlohmann_json через vcpkg
        git clone https://github.com/Microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh
        ./vcpkg/vcpkg install nlohmann-json

    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Debug -DENABLE_CODE_COVERAGE=ON -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build
      run: |
        cd build
        make

    - name: Test
      run: |
        cd build
        ctest -V

    - name: Generate code coverage report
      run: |
        sudo apt-get install -y lcov
        cd build
        lcov --capture --directory . --output-file coverage.info
        lcov --remove coverage.info '/usr/*' --output-file coverage.info
        lcov --list coverage.info

    - name: Upload coverage report
      uses: codecov/codecov-action@v3  # Обновлено с v1 до v3
      with:
        file: ./build/coverage.info
        flags: unittests
        name: codecov-umbrella

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3  # Обновлено с v2 до v3
      with:
        name: music-salon
        path: |
          bin/music_salon
          bin/music_salon_db.sql
          bin/resources/
